### ISSUE TITLE
Fix Publish in CI

### ISSUE THREAD

**Issue by amcdnl** [reaviz/rdk#2]
Need to fix the publish in CI

```
      - publish_storybook:
          filters:
            branches:
              only:
                - master
          requires:
            - build_storybook
            - build_package
```
